services:
  flask:
    build: .
    image: python:3.9-alpine
    container_name: flask
    ports:
      - 8000:5000 # DEBUG ONLY
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:5.0
    hostname: mongodb
    container_name: mongodb
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db_admin
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=flaskdb
